"""Render runs/<run_id>/audit.md from metadata + events + artifacts.

Idempotent: rerunning overwrites the file with current state.
"""
from __future__ import annotations

import pathlib

from lib import events as events_mod, metadata as metadata_mod
from lib.config import Config
from lib.metadata import run_dir


def _read_if_exists(path: pathlib.Path) -> str:
    if path.exists():
        return path.read_text().strip()
    return ""


def _summarize_artifact(label: str, path: pathlib.Path) -> str:
    if not path.exists():
        return f"- **{label}**: _not produced_"
    content = path.read_text().strip()
    if not content:
        return f"- **{label}** (`{path.name}`): _empty_"
    first_line = content.splitlines()[0] if content else ""
    return f"- **{label}** (`{path.name}`): {first_line[:120]}"


def render(cfg: Config, run_id: str) -> pathlib.Path:
    meta = metadata_mod.load(cfg, run_id)
    rd = run_dir(cfg, run_id)

    lines: list[str] = []
    out = lines.append

    out(f"# Audit — {run_id}")
    out("")
    out(f"_Generated by agent-workbench audit. Source of truth: `metadata.yaml` + `events.jsonl`._")
    out("")

    # Header
    out("## Header")
    out("")
    out(f"- **run_id**: `{meta['run_id']}`")
    out(f"- **status**: `{meta['status']}`")
    out(f"- **created_at**: {meta['created_at']}")
    out(f"- **updated_at**: {meta['updated_at']}")
    scope = meta.get("scope") or {}
    out(f"- **scope.kind**: {scope.get('kind', 'n/a')}")
    if scope.get("summary"):
        out(f"- **scope.summary**: {scope['summary']}")
    out("")

    # Target
    target = meta.get("target") or {}
    repo = target.get("repo") or {}
    wt = target.get("worktree") or {}
    out("## Target")
    out("")
    out(f"- **repo.mode**: {repo.get('mode')}")
    out(f"- **repo.path**: `{repo.get('path')}`")
    out(f"- **repo.name**: {repo.get('name')}")
    out(f"- **repo.base_ref**: {repo.get('base_ref')}")
    out(f"- **worktree.name**: {wt.get('name')}")
    out(f"- **worktree.branch_name**: `{wt.get('branch_name')}`")
    out(f"- **worktree.path**: `{wt.get('path')}`")
    out("")

    # Original request
    raw_path = rd / "raw-idea.md"
    out("## Original request")
    out("")
    if raw_path.exists():
        out("```text")
        out(_read_if_exists(raw_path))
        out("```")
    else:
        out("_no `raw-idea.md` recorded_")
    out("")

    # Pre-implementation records
    out("## Pre-implementation records")
    out("")
    out(_summarize_artifact("brief", rd / "brief.md"))
    out(_summarize_artifact("plan", rd / "plan.md"))
    out(_summarize_artifact("preflight", rd / "preflight.md"))
    out(_summarize_artifact("assumptions", rd / "assumptions.md"))
    out(_summarize_artifact("decisions", rd / "decisions.md"))
    out("")

    # Post-implementation records
    out("## Implementation & validation")
    out("")
    out(_summarize_artifact("implementation-summary", rd / "implementation-summary.md"))
    out(_summarize_artifact("diff-summary", rd / "diff-summary.md"))
    out(_summarize_artifact("review", rd / "review.md"))
    out(_summarize_artifact("qa report", rd / "qa" / "report.md"))
    out(_summarize_artifact("handoff", rd / "handoff.md"))
    out("")

    # Transition timeline
    out("## Transition timeline")
    out("")
    out("| seq | at | from -> to | actor | notes |")
    out("|---|---|---|---|---|")
    for ev in events_mod.iter_events(cfg, run_id):
        if ev.get("type") != "TransitionApplied":
            continue
        actor = ev.get("actor") or {}
        actor_label = f"{actor.get('type','?')}:{actor.get('name','?')}"
        notes = (ev.get("payload") or {}).get("notes") or ""
        out(
            f"| {ev['seq']} | {ev['at']} | "
            f"`{ev.get('from','?')}` -> `{ev.get('to','?')}` | "
            f"{actor_label} | {notes} |"
        )
    out("")

    # Notable secondary events
    out("## Notable events")
    out("")
    for ev in events_mod.iter_events(cfg, run_id):
        et = ev.get("type")
        if et in (
            "AssumptionRecorded",
            "DecisionRecorded",
            "WorktreeCreated",
            "BaseRefResolved",
            "ReviewCompleted",
            "QACompleted",
            "BounceRequested",
            "RunCompleted",
            "RunAbandoned",
            "ErrorRecorded",
        ):
            payload = ev.get("payload") or {}
            actor = ev.get("actor") or {}
            actor_label = f"{actor.get('type','?')}:{actor.get('name','?')}"
            summary = _payload_summary(et, payload)
            out(f"- **{et}** at {ev['at']} by {actor_label}: {summary}")
    out("")

    # Final status
    out("## Final status")
    out("")
    completion = meta.get("completion") or {}
    out(f"- **status**: `{meta['status']}`")
    if completion.get("accepted_by"):
        out(f"- **accepted_by**: {completion['accepted_by']}")
    if completion.get("completion_ref"):
        out(f"- **completion_ref**: `{completion['completion_ref']}`")
    if completion.get("completed_at"):
        out(f"- **completed_at**: {completion['completed_at']}")
    if completion.get("abandoned_reason"):
        out(f"- **abandoned_reason**: {completion['abandoned_reason']}")
    out("")

    audit_path = rd / "audit.md"
    audit_path.write_text("\n".join(lines))
    return audit_path


def _payload_summary(event_type: str, payload: dict) -> str:
    if event_type == "AssumptionRecorded":
        return f"`{payload.get('assumption_id','?')}` — {payload.get('text','')[:160]}"
    if event_type == "DecisionRecorded":
        return f"`{payload.get('decision_id','?')}` — {payload.get('decision','')[:160]}"
    if event_type == "WorktreeCreated":
        return f"branch `{payload.get('branch_name')}` at `{payload.get('worktree_path')}`"
    if event_type == "BaseRefResolved":
        sha = payload.get("base_ref_sha") or ""
        return f"`{payload.get('symbolic_ref','?')}` -> `{sha[:12]}`"
    if event_type == "ReviewCompleted":
        return f"decision={payload.get('review_decision')} report={payload.get('review_report_path')}"
    if event_type == "QACompleted":
        return f"tests_passed={payload.get('tests_passed')} report={payload.get('qa_report_path')}"
    if event_type == "BounceRequested":
        cr = payload.get("change_request_path")
        suffix = f" change_request=`{cr}`" if cr else ""
        return f"reason={payload.get('bounce_reason')}{suffix}"
    if event_type == "RunCompleted":
        return f"completion_ref={payload.get('completion_ref')} by={payload.get('accepted_by')}"
    if event_type == "RunAbandoned":
        return f"reason={payload.get('abandoned_reason')}"
    if event_type == "ErrorRecorded":
        return f"{payload.get('error_kind','?')}: {payload.get('message','')[:160]}"
    return ""
