"""Deterministic builder for `build-context.md`.

Curates the inputs the builder needs (acceptance criteria + non-goals from
brief, proposed changes + files + test plan + definition of done from plan,
all DR/ASM blocks, worktree metadata, and the build.md template skeleton)
into one file so the building session can read it instead of brief.md +
plan.md + templates/build.md separately.

Pure Python. No LLM call. Called from `cmd_start.run` after the worktree is
created and metadata is persisted, before the `ready -> building` transition.

Mirrors `lib/validate_context.py`'s shape. Helper functions are duplicated
(not imported from validate_context) because the two builders may diverge as
the other `<stage>-context.md` siblings land (TODO §1 items 2-4).
"""
from __future__ import annotations

import pathlib
import re


def build(
    *,
    brief_path: pathlib.Path,
    plan_path: pathlib.Path,
    meta: dict,
    build_template_path: pathlib.Path,
) -> str:
    """Return the rendered build-context.md body."""
    brief = _read(brief_path)
    plan = _read(plan_path)
    template = _read(build_template_path)

    sections: list[str] = []
    sections.append("# build-context.md\n")
    sections.append(
        "<!-- Generated by `start` at the `ready -> building` boundary. Read this "
        "instead of brief.md + plan.md + templates/build.md separately. -->\n"
    )

    sections.append("\n## Acceptance criteria\n")
    sections.append(_section(brief, "Acceptance criteria") or "(none in brief.md)\n")

    sections.append("\n## Non-goals\n")
    sections.append(_section(brief, "Non-goals") or "(none in brief.md)\n")

    sections.append("\n## Proposed changes\n")
    sections.append(_section(plan, "Proposed changes") or "(none in plan.md)\n")

    sections.append("\n## Files likely to change\n")
    sections.append(_section(plan, "Files likely to change") or "(none in plan.md)\n")

    sections.append("\n## Test plan\n")
    sections.append(_section(plan, "Test plan") or "(none in plan.md)\n")

    sections.append("\n## Definition of done\n")
    sections.append(_section(plan, "Definition of done") or "(none in plan.md)\n")

    sections.append("\n## Decisions & assumptions\n")
    sections.append(_all_plan_blocks(plan))

    sections.append("\n## Worktree\n")
    sections.append(_worktree_block(meta))

    sections.append("\n## build.md template skeleton\n")
    sections.append(template or "(templates/build.md missing or empty)\n")

    sections.append("\n## Rules\n")
    sections.append(_rules_block())

    return "".join(sections)


def write(path: pathlib.Path, body: str) -> None:
    """Idempotent write: parent dir is created if missing."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def _read(path: pathlib.Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)


def _section(body: str, name: str) -> str:
    """Return content under `## <name>` (any heading level) up to the next
    same-or-higher-level heading. Empty string if not found. Matches
    `lib/validate_context.py:_section`. HTML comments are stripped so unfilled
    template hints don't get parsed as real content.
    """
    if not body:
        return ""
    lines = body.splitlines(keepends=True)
    target = name.strip().lower()
    start: int | None = None
    start_level = 0
    for i, line in enumerate(lines):
        m = _HEADING_RE.match(line)
        if not m:
            continue
        level = len(m.group(1))
        title = m.group(2).strip().lower()
        if title == target:
            start = i + 1
            start_level = level
            break
    if start is None:
        return ""
    end = len(lines)
    for j in range(start, len(lines)):
        m = _HEADING_RE.match(lines[j])
        if m and len(m.group(1)) <= start_level:
            end = j
            break
    body_text = "".join(lines[start:end]).strip("\n") + "\n"
    return re.sub(r"<!--.*?-->", "", body_text, flags=re.DOTALL)


_BLOCK_ID_RE = re.compile(r"^#{2,4}\s+(DR-\d+|ASM-\d+)\s*$", re.MULTILINE)


def _all_plan_blocks(plan: str) -> str:
    """Return every DR-NNN / ASM-NNN block from plan.md, concatenated.

    Unlike `validate_context._filtered_plan_blocks` (which filters against
    `build.md`), we include all blocks here because `build.md` does not yet
    exist at building-entry time. The agent needs the full decision context
    to stay bounded.
    """
    if not plan:
        return "(plan.md missing or empty)\n"
    blocks = _collect_id_blocks(plan)
    if not blocks:
        return "(no DR-/ASM- blocks found in plan.md)\n"
    return "\n".join(blocks.values()) + "\n"


def _collect_id_blocks(plan: str) -> dict[str, str]:
    """Find every `### DR-NNN` / `### ASM-NNN` heading and the block under
    it (up to the next same-or-higher heading). Matches
    `lib/validate_context.py:_collect_id_blocks`.
    """
    lines = plan.splitlines(keepends=True)
    indices: list[tuple[str, int, int]] = []
    for i, line in enumerate(lines):
        m = _BLOCK_ID_RE.match(line)
        if not m:
            continue
        heading_match = _HEADING_RE.match(line)
        level = len(heading_match.group(1)) if heading_match else 3
        indices.append((m.group(1), level, i))

    out: dict[str, str] = {}
    for block_id, level, start in indices:
        end = len(lines)
        for j in range(start + 1, len(lines)):
            m = _HEADING_RE.match(lines[j])
            if m and len(m.group(1)) <= level:
                end = j
                break
        out[block_id] = "".join(lines[start:end]).rstrip() + "\n"
    return out


def _worktree_block(meta: dict) -> str:
    """Surface worktree path + branch name + base_ref_sha from metadata."""
    target = meta.get("target") or {}
    worktree = target.get("worktree") or {}
    repo = target.get("repo") or {}
    path = worktree.get("path") or "(not set)"
    branch = worktree.get("branch_name") or "(not set)"
    base_ref_sha = repo.get("base_ref_sha") or "(not set)"
    base_ref = repo.get("base_ref") or "(not set)"
    return (
        f"- **Path**: `{path}`\n"
        f"- **Branch**: `{branch}`\n"
        f"- **Base ref**: `{base_ref}`\n"
        f"- **Base ref SHA**: `{base_ref_sha}`\n"
    )


def _rules_block() -> str:
    return (
        "- Stay bounded by the brief's Acceptance criteria and Non-goals.\n"
        "- Record deviations from the plan in `build.md` under `Deviations from plan`.\n"
        "- Do not re-read `brief.md` or `plan.md` unless this file's sections are insufficient — "
        "the cache cost of those reads sticks in the session prefix forever.\n"
        "- Map every Acceptance criterion to a test path or an explicit "
        "'not tested — because …' justification in `build.md` under "
        "`Acceptance criteria coverage`.\n"
    )
