"""Deterministic builder for `followups-context.md`.

Curates the inputs the followups agent needs (brief's Non-goals, plan's
Risks, review's Decision + findings, qa report's Known issues, build's
Deviations from plan, the `follow-ups.md` schema, and the followups rules)
into one file so the followups session can read it instead of brief.md +
plan.md + build.md + review.md + qa/report.md + templates/follow-ups.md
separately.

Pure Python. No LLM call. Called from `cmd_followups.run` in `--init` mode,
after the `validating -> followups` transition completes (so the prior-stage
files have been moved into their `stages/N_<stage>/` dirs).

Mirrors `lib/build_context.py` / `lib/validate_context.py` shape. Helper
functions are duplicated (not imported from sibling generators) because the
family of builders may diverge as the contract evolves — see TODO §5.
"""
from __future__ import annotations

import pathlib
import re


def build(
    *,
    brief_path: pathlib.Path,
    plan_path: pathlib.Path,
    build_md_path: pathlib.Path,
    review_path: pathlib.Path,
    qa_report_path: pathlib.Path,
    followups_template_path: pathlib.Path,
) -> str:
    """Return the rendered followups-context.md body."""
    brief = _read(brief_path)
    plan = _read(plan_path)
    build_md = _read(build_md_path)
    review = _read(review_path)
    qa = _read(qa_report_path)
    template = _read(followups_template_path)

    sections: list[str] = []
    sections.append("# followups-context.md\n")
    sections.append(
        "<!-- Generated by `followups --init`. Read this instead of brief.md + "
        "plan.md + build.md + review.md + qa/report.md + templates/follow-ups.md "
        "separately. -->\n"
    )

    sections.append("\n## Brief: Non-goals\n")
    sections.append(_section(brief, "Non-goals") or "(none in brief.md)\n")

    sections.append("\n## Plan: Risks\n")
    sections.append(_section(plan, "Risks") or "(none in plan.md)\n")

    sections.append("\n## Review: Decision\n")
    sections.append(_section(review, "Decision") or "(none in review.md)\n")

    sections.append("\n## Review: Findings\n")
    sections.append(
        _section(review, "Findings")
        or _section(review, "Findings & remediations")
        or "(none in review.md)\n"
    )

    sections.append("\n## QA: Known issues\n")
    sections.append(
        _section(qa, "Known issues")
        or _section(qa, "Known issues / risks")
        or "(none in qa/report.md)\n"
    )

    sections.append("\n## Build: Deviations from plan\n")
    sections.append(
        _section(build_md, "Deviations from plan") or "(none in build.md)\n"
    )

    sections.append("\n## follow-ups.md schema\n")
    sections.append(template or "(templates/follow-ups.md missing or empty)\n")

    sections.append("\n## Rules\n")
    sections.append(_rules_block())

    return "".join(sections)


def write(path: pathlib.Path, body: str) -> None:
    """Idempotent write: parent dir is created if missing."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def _read(path: pathlib.Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)


def _section(body: str, name: str) -> str:
    """Return content under `## <name>` (any heading level) up to the next
    same-or-higher-level heading. Empty string if not found. Matches
    `lib/build_context.py:_section`.
    """
    if not body:
        return ""
    lines = body.splitlines(keepends=True)
    target = name.strip().lower()
    start: int | None = None
    start_level = 0
    for i, line in enumerate(lines):
        m = _HEADING_RE.match(line)
        if not m:
            continue
        level = len(m.group(1))
        title = m.group(2).strip().lower()
        if title == target:
            start = i + 1
            start_level = level
            break
    if start is None:
        return ""
    end = len(lines)
    for j in range(start, len(lines)):
        m = _HEADING_RE.match(lines[j])
        if m and len(m.group(1)) <= start_level:
            end = j
            break
    return "".join(lines[start:end]).strip("\n") + "\n"


def _rules_block() -> str:
    return (
        "- Read-only stage. Do not modify code or prior artifacts.\n"
        "- Write 1–5 entries OR a single `no_followups` sentinel entry. The "
        "CLI rejects empty files and files with more than 5 entries.\n"
        "- Each entry's YAML frontmatter must have `title`, `motivation`, "
        "`suggested_scope`, `category`. Category is the enum: `tech_debt | "
        "scope_extension | bug_risk | refactor | docs | deferred_from_bounce "
        "| no_followups`.\n"
        "- Do not re-read `brief.md`, `plan.md`, `build.md`, `review.md`, or "
        "`qa/report.md` separately if this file's sections are insufficient — "
        "the cache cost of those reads sticks in the session prefix forever.\n"
    )
