"""Deterministic builder for `plan-context.md`.

Curates the inputs the planning agent needs (full brief.md, a repo-map block
detected from the target worktree's manifest files, the brief's "Files
likely to change" section, worktree metadata, the plan.md template skeleton,
and the planning rules) into one file so the planning session can read it
instead of brief.md + templates/plan.md separately.

Pure Python. No LLM call. Called from `cmd_plan.run` in `--init` mode, after
the planning templates are staged.

Mirrors `lib/build_context.py` / `lib/validate_context.py` shape. Helper
functions are duplicated (not imported from sibling generators) because the
family of builders may diverge as the contract evolves — see TODO §5.

Repo-map detection is intentionally narrow: only canonical manifest files at
the worktree root are recognized (pyproject.toml, package.json, Cargo.toml,
go.mod, Makefile). Heuristic scanning of source files is rejected as too
noisy. If no manifest matches, the map reports "no recognized manifests at
worktree root" plus the top-level directory list.
"""
from __future__ import annotations

import pathlib
import re


def build(
    *,
    brief_path: pathlib.Path,
    plan_template_path: pathlib.Path,
    worktree_path: str | None,
    meta: dict,
) -> str:
    """Return the rendered plan-context.md body."""
    brief = _read(brief_path)
    template = _read(plan_template_path)

    sections: list[str] = []
    sections.append("# plan-context.md\n")
    sections.append(
        "<!-- Generated by `plan --init`. Read this instead of brief.md + "
        "templates/plan.md separately. -->\n"
    )

    sections.append("\n## Brief\n")
    sections.append(brief or "(brief.md missing or empty)\n")

    sections.append("\n## Repo map\n")
    sections.append(_detect_repo_map(worktree_path))

    sections.append("\n## Files likely to change (from brief)\n")
    sections.append(
        _section(brief, "Files likely to change") or "(none in brief.md)\n"
    )

    sections.append("\n## Worktree\n")
    sections.append(_worktree_block(meta))

    sections.append("\n## plan.md template skeleton\n")
    sections.append(template or "(templates/plan.md missing or empty)\n")

    sections.append("\n## Rules\n")
    sections.append(_rules_block())

    return "".join(sections)


def write(path: pathlib.Path, body: str) -> None:
    """Idempotent write: parent dir is created if missing."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def _read(path: pathlib.Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)


def _section(body: str, name: str) -> str:
    """Return content under `## <name>` (any heading level) up to the next
    same-or-higher-level heading. Empty string if not found. Matches
    `lib/build_context.py:_section`.
    """
    if not body:
        return ""
    lines = body.splitlines(keepends=True)
    target = name.strip().lower()
    start: int | None = None
    start_level = 0
    for i, line in enumerate(lines):
        m = _HEADING_RE.match(line)
        if not m:
            continue
        level = len(m.group(1))
        title = m.group(2).strip().lower()
        if title == target:
            start = i + 1
            start_level = level
            break
    if start is None:
        return ""
    end = len(lines)
    for j in range(start, len(lines)):
        m = _HEADING_RE.match(lines[j])
        if m and len(m.group(1)) <= start_level:
            end = j
            break
    return "".join(lines[start:end]).strip("\n") + "\n"


def _worktree_block(meta: dict) -> str:
    """Surface worktree path + branch name + base_ref(_sha) from metadata."""
    target = meta.get("target") or {}
    worktree = target.get("worktree") or {}
    repo = target.get("repo") or {}
    path = worktree.get("path") or "(not set)"
    branch = worktree.get("branch_name") or "(not set)"
    base_ref_sha = repo.get("base_ref_sha") or "(not set)"
    base_ref = repo.get("base_ref") or "(not set)"
    return (
        f"- **Path**: `{path}`\n"
        f"- **Branch**: `{branch}`\n"
        f"- **Base ref**: `{base_ref}`\n"
        f"- **Base ref SHA**: `{base_ref_sha}`\n"
    )


def _detect_repo_map(worktree_path: str | None) -> str:
    """Return a curated repo-map block for the target worktree.

    Recognized manifests (root-only, no recursive scanning):

    - ``pyproject.toml`` → Python
    - ``package.json`` → JavaScript / TypeScript
    - ``Cargo.toml`` → Rust
    - ``go.mod`` → Go
    - ``Makefile`` → check for `test:` / `build:` / `lint:` targets

    Plus top-level directory listing (depth 1, filtered: skip dotfiles,
    ``node_modules``, ``__pycache__``).
    """
    if not worktree_path:
        return "(worktree not yet created — repo-map unavailable at draft time)\n"
    root = pathlib.Path(worktree_path)
    if not root.exists() or not root.is_dir():
        return f"(worktree path `{worktree_path}` does not exist or is not a directory)\n"

    out: list[str] = []

    out.append("**Top-level directories**\n\n")
    dirs = _top_level_dirs(root)
    if dirs:
        for d in dirs:
            out.append(f"- `{d}/`\n")
    else:
        out.append("- (no top-level directories detected)\n")

    out.append("\n**Detected languages**\n\n")
    languages = _detect_languages(root)
    if languages:
        for label in languages:
            out.append(f"- {label}\n")
    else:
        out.append("- (no recognized manifests at worktree root)\n")

    out.append("\n**Build / test commands**\n\n")
    commands = _detect_commands(root)
    if commands:
        for label in commands:
            out.append(f"- {label}\n")
    else:
        out.append("- (no commands detected from manifests)\n")

    return "".join(out)


_SKIP_DIRS = {"node_modules", "__pycache__", "dist", "build", ".git", ".venv", "venv"}


def _top_level_dirs(root: pathlib.Path) -> list[str]:
    out: list[str] = []
    try:
        for child in sorted(root.iterdir()):
            if not child.is_dir():
                continue
            name = child.name
            if name.startswith("."):
                continue
            if name in _SKIP_DIRS:
                continue
            out.append(name)
    except OSError:
        return []
    return out


def _detect_languages(root: pathlib.Path) -> list[str]:
    out: list[str] = []
    if (root / "pyproject.toml").is_file():
        out.append("Python (`pyproject.toml`)")
    if (root / "setup.py").is_file() and "Python (`pyproject.toml`)" not in out:
        out.append("Python (`setup.py`)")
    if (root / "package.json").is_file():
        out.append("JavaScript/TypeScript (`package.json`)")
    if (root / "Cargo.toml").is_file():
        out.append("Rust (`Cargo.toml`)")
    if (root / "go.mod").is_file():
        out.append("Go (`go.mod`)")
    return out


_MAKEFILE_TARGET_RE = re.compile(r"^([A-Za-z][A-Za-z0-9_./-]*)\s*:", re.MULTILINE)
_INTERESTING_MAKE_TARGETS = ("test", "build", "lint", "check", "fmt", "format", "typecheck")


def _detect_commands(root: pathlib.Path) -> list[str]:
    out: list[str] = []
    # pyproject.toml: look for [tool.pytest], or default to `pytest`.
    pyproject = root / "pyproject.toml"
    if pyproject.is_file():
        text = _read(pyproject)
        if "[tool.pytest" in text:
            out.append("Python: `pytest` (configured in `[tool.pytest]`)")
        else:
            out.append("Python: `python -m pytest` (default)")

    # package.json: lift scripts block keys if present.
    pkg = root / "package.json"
    if pkg.is_file():
        text = _read(pkg)
        scripts = _extract_package_json_scripts(text)
        if scripts:
            out.append(
                "Node: scripts available — "
                + ", ".join(f"`npm run {name}`" for name in scripts)
            )

    # Cargo.toml: default `cargo test`.
    if (root / "Cargo.toml").is_file():
        out.append("Rust: `cargo test`, `cargo build`")

    # go.mod: default `go test ./...`.
    if (root / "go.mod").is_file():
        out.append("Go: `go test ./...`, `go build ./...`")

    # Makefile: lift interesting target names.
    mk = root / "Makefile"
    if mk.is_file():
        text = _read(mk)
        targets = sorted({
            m.group(1)
            for m in _MAKEFILE_TARGET_RE.finditer(text)
            if m.group(1) in _INTERESTING_MAKE_TARGETS
        })
        if targets:
            out.append(
                "Makefile: targets — "
                + ", ".join(f"`make {t}`" for t in targets)
            )
    return out


_PKG_SCRIPTS_BLOCK_RE = re.compile(
    r'"scripts"\s*:\s*\{([^}]*)\}', re.DOTALL,
)
_PKG_SCRIPT_KEY_RE = re.compile(r'"([^"]+)"\s*:\s*"')


def _extract_package_json_scripts(text: str) -> list[str]:
    """Return ordered script names from a package.json's scripts block.

    Permissive parser; returns [] if the file isn't shaped like a normal
    package.json. We don't take a JSON dependency here — the file might
    have comments (some projects do), and we only want the key names.
    """
    m = _PKG_SCRIPTS_BLOCK_RE.search(text)
    if not m:
        return []
    block = m.group(1)
    return _PKG_SCRIPT_KEY_RE.findall(block)


def _rules_block() -> str:
    return (
        "- You MAY read code in the target repo's worktree. Planning is the "
        "first stage that's code-aware.\n"
        "- Do NOT ask the user questions. Only `/draft` may. Convert any "
        "remaining ambiguity into Assumptions (ASM-NNN) in `plan.md` and "
        "choose the safest small implementation.\n"
        "- Do not re-read `brief.md` separately unless this file's Brief "
        "section is insufficient — the cache cost of those reads sticks in "
        "the session prefix forever.\n"
        "- If the task is too broad, reduce scope and note in the plan what "
        "was deferred.\n"
        "- Spawn `Explore` subagents for multi-file repo mapping (more than "
        "3 files for understanding, not editing). See "
        "`agent-workbench-live/AGENTS.md` § \"Subagent discipline\".\n"
    )
