"""Deterministic builder for `shape-context.md`.

Curates the inputs the shaping agent needs (raw-idea.md verbatim, answers.md
verbatim if present, brief.md template skeleton inlined) into one file so the
shaping session can read it instead of raw-idea.md + answers.md +
templates/brief.md separately.

Pure Python. No LLM call. Called from `cmd_shape.run` in `--init` mode, after
the brief.md template is staged and before the `ArtifactWritten` event is
emitted.

Mirrors `lib/build_context.py`'s shape. Helper functions are duplicated (not
imported from build_context) because the family of builders may diverge as
the contract evolves — see TODO §5.
"""
from __future__ import annotations

import pathlib


def build(
    *,
    raw_idea_path: pathlib.Path,
    answers_path: pathlib.Path | None,
    brief_template_path: pathlib.Path,
) -> str:
    """Return the rendered shape-context.md body."""
    raw_idea = _read(raw_idea_path)
    answers = _read(answers_path) if answers_path is not None else ""
    template = _read(brief_template_path)

    sections: list[str] = []
    sections.append("# shape-context.md\n")
    sections.append(
        "<!-- Generated by `shape --init`. Read this instead of raw-idea.md + "
        "answers.md + templates/brief.md separately. -->\n"
    )

    sections.append("\n## Raw idea\n")
    sections.append(raw_idea or "(raw-idea.md missing or empty)\n")

    if answers_path is not None and answers.strip():
        sections.append("\n## Answers\n")
        sections.append(answers)

    sections.append("\n## brief.md template skeleton\n")
    sections.append(template or "(templates/brief.md missing or empty)\n")

    sections.append("\n## Rules\n")
    sections.append(_rules_block())

    return "".join(sections)


def write(path: pathlib.Path, body: str) -> None:
    """Idempotent write: parent dir is created if missing."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def _read(path: pathlib.Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def _rules_block() -> str:
    return (
        "- Do NOT read code in the target repo. Shaping is code-blind.\n"
        "- Do NOT ask the user questions. Only `/draft` may. Convert any "
        "remaining ambiguity into Assumptions in `brief.md`.\n"
        "- Do not re-read `raw-idea.md`, `answers.md`, or "
        "`templates/brief.md` unless this file's sections are insufficient — "
        "the cache cost of those reads sticks in the session prefix forever.\n"
        "- Be specific. Bad examples and Non-goals are as important as the "
        "Goal.\n"
    )
