"""Deterministic builder for `validate-context.md`.

Curates the inputs the validator needs (original task, acceptance criteria,
filtered plan decisions/assumptions, diff, files changed, commands run, test
results, known issues, reviewer reading order) into one file so the validator
session can read it instead of brief.md + plan.md + build.md + qa/report.md
separately.

Pure Python. No LLM call. Called from `cmd_validate._init()` after templates
are staged and before the `building -> validating` transition.
"""
from __future__ import annotations

import pathlib
import re
import subprocess
from typing import Iterable


_FULL_DIFF_LINE_CAP = 500
_BLAST_RADIUS_LINE_CAP = 200
_BLAST_RADIUS_FILE_CAP = 500


def build(
    *,
    brief_path: pathlib.Path,
    plan_path: pathlib.Path,
    build_md_path: pathlib.Path,
    qa_report_path: pathlib.Path,
    worktree_path: str,
    base_ref: str,
    base_ref_sha: str | None = None,
) -> str:
    """Return the rendered validate-context.md body.

    ``base_ref_sha`` is the resolved 40-char SHA captured at ``/start`` time
    (TODO §3 item 2a). When present, diff ranges use the SHA rather than the
    symbolic ``base_ref`` — this is what makes ``git diff <ref>...HEAD``
    produce a non-empty diff for runs whose ``base_ref`` is the symbolic
    ``"HEAD"`` (which would otherwise diff the worktree against itself).
    Falls back to lazy resolution in the worktree, then to symbolic, matching
    ``lib/metrics/lines.py:_effective_ref``.
    """
    brief = _read(brief_path)
    plan = _read(plan_path)
    build_md = _read(build_md_path)
    qa = _read(qa_report_path)

    effective_ref = _effective_ref(worktree_path, base_ref, base_ref_sha)

    sections: list[str] = []
    sections.append("# validate-context.md\n")
    sections.append(
        "<!-- Generated by `validate --init`. Read this instead of brief/plan/build/qa "
        "separately. Pass-2 (B2). -->\n"
    )

    sections.append("## Original task\n")
    sections.append(_section(brief, "Goal") or "(brief.md missing or empty)\n")
    behavior = _section(brief, "User-facing behavior")
    if behavior:
        sections.append("\n### User-facing behavior\n")
        sections.append(behavior)

    sections.append("\n## Acceptance criteria\n")
    sections.append(_section(brief, "Acceptance criteria") or "(none in brief.md)\n")

    sections.append("\n## Plan decisions + assumptions (filtered)\n")
    sections.append(_filtered_plan_blocks(plan, build_md))

    sections.append("\n## Final diff\n")
    sections.append(_render_diff(worktree_path, effective_ref))

    sections.append("\n## Files changed\n")
    sections.append(_render_name_status(worktree_path, effective_ref))

    sections.append("\n## Commands run\n")
    sections.append(_section(build_md, "Commands run") or "(none recorded in build.md)\n")

    sections.append("\n## Test results\n")
    test_section = _section(qa, "Test results") or _section(qa, "Results")
    sections.append(test_section or "(see qa/report.md)\n")

    sections.append("\n## Known issues / risks\n")
    sections.append(_section(build_md, "Known issues") or "(none recorded in build.md)\n")

    sections.append("\n## Reviewer reading order\n")
    sections.append(
        _section(build_md, "Reviewer reading order")
        or _default_reading_order()
    )

    return "".join(sections)


def write(path: pathlib.Path, body: str) -> None:
    """Idempotent write: parent dir is created if missing."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def _read(path: pathlib.Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)


def _section(body: str, name: str) -> str:
    """Return the content under `## <name>` (or any heading level) up to the
    next same-or-higher-level heading. Returns empty string if not found.
    HTML comments are stripped so unfilled template hints don't get parsed
    as real content."""
    if not body:
        return ""
    lines = body.splitlines(keepends=True)
    target = name.strip().lower()
    start: int | None = None
    start_level = 0
    for i, line in enumerate(lines):
        m = _HEADING_RE.match(line)
        if not m:
            continue
        level = len(m.group(1))
        title = m.group(2).strip().lower()
        if title == target:
            start = i + 1
            start_level = level
            break
    if start is None:
        return ""
    end = len(lines)
    for j in range(start, len(lines)):
        m = _HEADING_RE.match(lines[j])
        if m and len(m.group(1)) <= start_level:
            end = j
            break
    body_text = "".join(lines[start:end]).strip("\n") + "\n"
    return re.sub(r"<!--.*?-->", "", body_text, flags=re.DOTALL)


_BLOCK_ID_RE = re.compile(r"^#{2,4}\s+(DR-\d+|ASM-\d+)\s*$", re.MULTILINE)


def _filtered_plan_blocks(plan: str, build_md: str) -> str:
    """Extract DR-NNN / ASM-NNN blocks from plan; keep only ones referenced
    in build_md. If build_md references none, include all (fallback).
    """
    if not plan:
        return "(plan.md missing or empty)\n"
    blocks = _collect_id_blocks(plan)
    if not blocks:
        return "(no DR-/ASM- blocks found in plan.md)\n"
    referenced = set()
    if build_md:
        for m in re.finditer(r"\b((?:DR|ASM)-\d+)\b", build_md):
            referenced.add(m.group(1))
    if not referenced:
        # Fallback — no references found, include all.
        keep = list(blocks.keys())
    else:
        keep = [k for k in blocks.keys() if k in referenced]
    if not keep:
        return "(plan has DR-/ASM- blocks but none are referenced in build.md)\n"
    out = []
    for k in keep:
        out.append(blocks[k])
    return "\n".join(out) + "\n"


def _collect_id_blocks(plan: str) -> dict[str, str]:
    """Find every `### DR-NNN` / `### ASM-NNN` heading and the block under
    it (up to the next same-or-higher heading)."""
    lines = plan.splitlines(keepends=True)
    indices: list[tuple[str, int, int]] = []  # (id, level, line_index)
    for i, line in enumerate(lines):
        m = _BLOCK_ID_RE.match(line)
        if m:
            level = len(line) - len(line.lstrip("#"))  # crude level count
            # Recompute level cleanly:
            heading_match = _HEADING_RE.match(line)
            if heading_match:
                level = len(heading_match.group(1))
            indices.append((m.group(1), level, i))

    out: dict[str, str] = {}
    for idx, (block_id, level, start) in enumerate(indices):
        end = len(lines)
        # Find the next heading at same-or-higher level.
        for j in range(start + 1, len(lines)):
            m = _HEADING_RE.match(lines[j])
            if m and len(m.group(1)) <= level:
                end = j
                break
        out[block_id] = "".join(lines[start:end]).rstrip() + "\n"
    return out


def _render_diff(worktree_path: str, base_ref: str) -> str:
    """Always include `git diff --stat`. Include full `git diff` only if it
    fits in `_FULL_DIFF_LINE_CAP`; otherwise include `--name-status` plus
    per-file line counts and a note.

    Covers BOTH committed and uncommitted changes (TODO §3 item 2a follow-on):
    the committed range ``<base_ref>...HEAD`` plus the uncommitted delta
    ``HEAD``. Validation typically runs before the builder has committed —
    showing only committed changes would render an empty diff for the
    common case where the work is staged or unstaged in the worktree but
    not yet committed.
    """
    parts: list[str] = []

    stat = _git(worktree_path, "diff", "--stat", f"{base_ref}...HEAD")
    if stat is None:
        return "(git diff --stat failed; see worktree directly)\n"
    parts.append(f"```\n{stat}```\n")
    full = _git(worktree_path, "diff", f"{base_ref}...HEAD")
    if full is not None and full.strip():
        line_count = full.count("\n")
        if line_count <= _FULL_DIFF_LINE_CAP:
            parts.append(f"\n```diff\n{full}```\n")
        else:
            parts.append(
                f"\n(full committed diff is {line_count} lines; exceeds {_FULL_DIFF_LINE_CAP}-line cap. "
                "See `Files changed` below for per-file line counts.)\n"
            )

    # Uncommitted changes (staged + unstaged, including untracked via name-status).
    uncommitted_stat = _git(worktree_path, "diff", "HEAD", "--stat")
    if uncommitted_stat and uncommitted_stat.strip():
        parts.append("\n### Uncommitted (worktree vs HEAD)\n")
        parts.append(f"```\n{uncommitted_stat}```\n")
        uncommitted_full = _git(worktree_path, "diff", "HEAD")
        if uncommitted_full is not None and uncommitted_full.strip():
            line_count = uncommitted_full.count("\n")
            if line_count <= _FULL_DIFF_LINE_CAP:
                parts.append(f"\n```diff\n{uncommitted_full}```\n")
            else:
                parts.append(
                    f"\n(full uncommitted diff is {line_count} lines; exceeds {_FULL_DIFF_LINE_CAP}-line cap. "
                    "See `Files changed` below.)\n"
                )

    return "".join(parts)


def _render_name_status(worktree_path: str, base_ref: str) -> str:
    """Files changed: committed (<base>...HEAD) plus uncommitted (HEAD vs worktree)
    plus untracked. Concatenated with section sub-headings when any class is present.
    """
    committed = _git(worktree_path, "diff", "--name-status", f"{base_ref}...HEAD")
    uncommitted = _git(worktree_path, "diff", "--name-status", "HEAD")
    untracked = _git(worktree_path, "ls-files", "--others", "--exclude-standard")

    have_committed = committed is not None and committed.strip()
    have_uncommitted = uncommitted is not None and uncommitted.strip()
    have_untracked = untracked is not None and untracked.strip()

    if not (have_committed or have_uncommitted or have_untracked):
        if committed is None and uncommitted is None:
            return "(git diff --name-status failed)\n"
        return "(no files changed yet)\n"

    parts: list[str] = []
    if have_committed:
        parts.append("**Committed** (`<base_ref>...HEAD`):\n")
        parts.append(f"```\n{committed}```\n")
    if have_uncommitted:
        parts.append("\n**Uncommitted** (worktree vs `HEAD`):\n")
        parts.append(f"```\n{uncommitted}```\n")
    if have_untracked:
        parts.append("\n**Untracked** (not yet `git add`-ed):\n")
        parts.append(f"```\n{untracked}```\n")
    return "".join(parts)


def _default_reading_order() -> str:
    return (
        "(no explicit `## Reviewer reading order` in build.md — defaults:)\n\n"
        "1. brief.md → Acceptance criteria — confirm scope.\n"
        "2. plan.md → Decisions & assumptions — confirm load-bearing trade-offs.\n"
        "3. build.md → Implementation summary + Files changed.\n"
        "4. review.md (this stage authors it) — adversarial findings.\n"
        "5. qa/report.md — what ran, what passed, what failed.\n"
        "6. stages/5_validating/blast-radius.txt — callers depth 1-3.\n"
    )


def _git(worktree_path: str, *args: str) -> str | None:
    if not worktree_path:
        return None
    if not pathlib.Path(worktree_path).exists():
        return None
    try:
        proc = subprocess.run(
            ["git", "-C", worktree_path, *args],
            capture_output=True, text=True, check=False,
        )
    except FileNotFoundError:
        return None
    if proc.returncode != 0:
        return None
    return proc.stdout


def _effective_ref(worktree_path: str, base_ref: str, base_ref_sha: str | None) -> str:
    """Prefer the resolved SHA; lazily resolve in the worktree; else symbolic.

    Mirrors ``lib/metrics/lines.py:_effective_ref``. Kept local to avoid a
    cross-module dependency for a six-line utility (DR-001). Deviates from
    the metrics version by adding an early-return guard for a missing
    worktree path — harmless extra defense; harmonize at promotion time.
    """
    if base_ref_sha:
        return base_ref_sha
    if not worktree_path or not pathlib.Path(worktree_path).exists():
        return base_ref
    try:
        proc = subprocess.run(
            ["git", "-C", worktree_path, "rev-parse", "--verify", base_ref],
            capture_output=True, text=True, check=False,
        )
    except FileNotFoundError:
        return base_ref
    if proc.returncode == 0:
        sha = proc.stdout.strip()
        if sha:
            return sha
    return base_ref


# ----- Blast radius (B4) ------------------------------------------------------

_DIFF_HUNK_RE = re.compile(r"^@@.*@@", re.MULTILINE)
_PY_SYMBOL_RE = re.compile(
    r"^[+\-]?\s*(?:def|class|async def)\s+([A-Za-z_][A-Za-z0-9_]*)",
    re.MULTILINE,
)


def build_blast_radius(
    *,
    worktree_path: str,
    base_ref: str,
    base_ref_sha: str | None = None,
) -> str:
    """Compute the depth-1/2/3 caller tree as a small text file.

    Covers committed + uncommitted + untracked changes. Validation often runs
    before the builder has committed, so committed-only diffs render empty
    in the common case. Same rationale as ``_render_diff``.
    """
    if not worktree_path or not pathlib.Path(worktree_path).exists():
        return "(worktree not available)\n"
    effective_ref = _effective_ref(worktree_path, base_ref, base_ref_sha)
    committed = _git(worktree_path, "diff", "--name-only", f"{effective_ref}...HEAD") or ""
    uncommitted = _git(worktree_path, "diff", "--name-only", "HEAD") or ""
    untracked = _git(worktree_path, "ls-files", "--others", "--exclude-standard") or ""
    files = sorted({
        ln for ln in (committed + "\n" + uncommitted + "\n" + untracked).splitlines()
        if ln.strip()
    })
    if not files:
        return "(no files changed yet)\n"
    if len(files) > _BLAST_RADIUS_FILE_CAP:
        return (
            f"(blast radius not computed: diff has {len(files)} files, "
            f"exceeds cap of {_BLAST_RADIUS_FILE_CAP})\n"
        )

    out_lines: list[str] = []
    out_lines.append("depth 1 (changed files):")
    for f in files:
        out_lines.append(f"  {f}")
    out_lines.append("")

    # depth-2: symbols modified in each file → callers.
    out_lines.append("depth 2 (callers of changed symbols):")
    depth2_files: set[str] = set()
    for f in files:
        # Try committed range first; fall back to uncommitted (HEAD vs worktree)
        # for files only in the uncommitted/untracked sets.
        diff_for_file = (
            _git(worktree_path, "diff", f"{effective_ref}...HEAD", "--", f)
            or _git(worktree_path, "diff", "HEAD", "--", f)
            or ""
        )
        if not diff_for_file.strip():
            # Untracked file — read it directly so symbol extraction still works.
            try:
                diff_for_file = (pathlib.Path(worktree_path) / f).read_text(
                    encoding="utf-8", errors="ignore",
                )
            except OSError:
                continue
        if not diff_for_file:
            continue
        symbols = set()
        for m in _PY_SYMBOL_RE.finditer(diff_for_file):
            symbols.add(m.group(1))
        for sym in sorted(symbols):
            callers = _grep_callers(worktree_path, sym, exclude=f)
            if not callers:
                continue
            out_lines.append(f"  {f}:{sym}  -> {', '.join(sorted(callers))}")
            depth2_files.update(callers)
        if _line_count(out_lines) >= _BLAST_RADIUS_LINE_CAP:
            out_lines.append("  (truncated at line cap)")
            break
    out_lines.append("")

    # depth-3: callers of those callers.
    out_lines.append("depth 3 (callers of those callers):")
    seen_depth3 = set()
    for d2 in sorted(depth2_files):
        if _line_count(out_lines) >= _BLAST_RADIUS_LINE_CAP:
            out_lines.append("  (truncated at line cap)")
            break
        # crude: extract symbols defined in this depth-2 file, look one hop out
        try:
            text = (pathlib.Path(worktree_path) / d2).read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for m in _PY_SYMBOL_RE.finditer(text):
            sym = m.group(1)
            if sym in seen_depth3:
                continue
            seen_depth3.add(sym)
            callers = _grep_callers(worktree_path, sym, exclude=d2)
            if callers:
                out_lines.append(f"  {d2}:{sym}  -> {', '.join(sorted(list(callers))[:5])}")
            if _line_count(out_lines) >= _BLAST_RADIUS_LINE_CAP:
                out_lines.append("  (truncated at line cap)")
                break

    return "\n".join(out_lines) + "\n"


def _grep_callers(worktree_path: str, symbol: str, *, exclude: str) -> set[str]:
    out = _git(worktree_path, "grep", "-l", "-w", symbol)
    if not out:
        return set()
    return {ln.strip() for ln in out.splitlines() if ln.strip() and ln.strip() != exclude}


def _line_count(lines: Iterable[str]) -> int:
    return sum(1 for _ in lines)
